name: "Lag release1"

on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'versjonsnummer.'
        required: true

jobs:
  build:
    name: 'Lag release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Sett git-config
      #   run: |
      #     git config user.name "Github actions"
      #     git config user.email noreply@github.com

      #lager release branch
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Push upstream release branch
        run: git push origin release/${{ github.event.inputs.version }}

      - name: log branch name
        run: echo "branchname ${{github.ref}}"

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ github.event.inputs.version }} 
          #${{ github.ref }}
          base: main
          title: "Release/${{ github.event.inputs.version }}"