name: "Lag release1"

on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'versjonsnummer.'
        required: true

jobs:
  build:
    name: 'Lag release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sett git-config
        run: |
          git config user.name "Github actions"
          git config user.email noreply@github.com

      - name: Create release branch
        run: git checkout -b Release/${{ github.event.inputs.version }}

      - name: Push ny branch
        run: git push origin Release/${{ github.event.inputs.version }}

      - name: Lag pull request to master
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: main
          title: Release version ${{ github.event.inputs.version }} til master
          body: |
            Hei @${{ github.actor }}!
            Generert melding om PR
           
            Merging this PR will create a GitHub release.