name: Create a hotfix and pull-request

on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'versjonsnummer.'
        required: true
      type:
        description: "type: hotfix"
        required: true
jobs:
  hotfix:
    if: contains(${{github.event.inputs.type}}, 'hotfix' || 'Hotfix')
    name: 'Lag release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Sett git-config
      #   run: |
      #     git config user.name "Github actions"
      #     git config user.email noreply@github.com

      - name: bytt branch develop
        run: git checkout ${{github.ref}}

      # lager release branch
       
      - name: Create release branch
        run: git checkout -b hotfix/${{ github.event.inputs.version }}

      - name: Push upstream hotfix branch
        run: git push origin hotfix/${{ github.event.inputs.version }}

      - name: log branch name
        run: echo "branchname ${{github.ref}}"
        # lager github-release
      - name: Create Hotfix
        id: create_hotfix
        uses: actions/create-release@v1
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: hotfix/${{ github.event.inputs.version }}
          body: 'Beskrivelse av hotfix'
          draft: false

  pull-request:
    needs: hotfix
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: hotfix/${{ github.event.inputs.version }} 
          base: main
          title: "Hotfix/${{ github.event.inputs.version }}"
