name: Create a release pull-request
on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'versjonsnummer.'
        required: true
jobs:
  build:
    name: 'Lag release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Sett git-config
      #   run: |
      #     git config user.name "Github actions"
      #     git config user.email noreply@github.com

      - name: bytt branch develop
        run: git checkout ${{github.ref}}

      # lager release branch
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Push upstream release branch
        run: git push origin release/${{ github.event.inputs.version }}

      - name: log branch name
        run: echo "branchname ${{github.ref}}"

  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      # - name: checkout
      #   uses: actions/checkout@v1
      - name: create-release-pr
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: main
          head: release/${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: a,b,c
          assign: true