
name: Create a release and pull-request

on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'versjonsnummer.'
        required: true
      type:
        description: "type: release/hotfix"
        required: true
jobs:
  release:
    # if: contains(${github.event.inputs.type}:lower(), 'release')

    name: 'Lag release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Sett git-config
      #   run: |
      #     git config user.name "Github actions"
      #     git config user.email noreply@github.com

      - name: bytt branch develop
        run: git checkout ${{github.ref}}

      # lager release branch
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release/${{ github.event.inputs.version }}
          body: 'Beskrivelse av release'
          draft: false
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: Release/${{ github.event.inputs.version }} 
          base: main
          title: "Release/${{ github.event.inputs.version }}"
  test_job:
    if: contains(${{lower(github.event.inputs.type)}}, 'release')
    name: 'test jobb'
    runs-on: ubuntu-latest
    steps:
      - name: 'write yes'
        run: echo 'yes'

